# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/google/gtfs-realtime-bindings"

[metadata.heroku]
  root-package = "github.com/jeffreylo/mtapi"
  go-version = "go1.10"
  install = ["./..."]
